---
version: "3.9"
services:
  db:
    image: mongo:latest
    container_name: db
    volumes:
      - ./db/data:/data/db
    ports:
      - 3001:27017
    environment:
      - MONGO_INITDB_ROOT_USERNAME=mnystoriak
      - MONGO_INITDB_ROOT_PASSWORD=64yrHFNV